export const boardCardObject = {
  x: 0,
  y: 0,
  originalX: 0,
  originalY: 0,
  color: "black",
  goldCount: 0,
  isWall: false,
  isTeleporter: false,
  isGold: false,
  isMine: false,
  isCharacter: false,
  isBullet: false,
  direction: "none",
};

export function board() {
  const board = [];

  for (let i = 0; i < 300; i += 10) {
    board.push({ ...boardCardObject, x: 0, y: i, isWall: true });
    board.push({ ...boardCardObject, x: 490, y: i, isWall: true });
  }

  for (let i = 0; i < 300; i += 10) {
    if (i === 50 || i === 240) continue;
    board.push({ ...boardCardObject, x: 90, y: i, isWall: true });
    board.push({ ...boardCardObject, x: 390, y: i, isWall: true });
    board.push({ ...boardCardObject, x: 290, y: i, isWall: true });
    board.push({ ...boardCardObject, x: 190, y: i, isWall: true });
  }

  for (let i = 10; i < 500; i += 10) {
    board.push({ ...boardCardObject, x: i, y: 0, isWall: true });
  }

  for (let i = 10; i < 500; i += 10) {
    board.push({ ...boardCardObject, x: i, y: 290, isWall: true });
  }

  for (let i = 10; i < 500; i += 10) {
    if (i === 240) continue;
    board.push({ ...boardCardObject, x: i, y: 190, isWall: true });
  }

  for (let i = 10; i < 500; i += 10) {
    if (i === 240) continue;
    board.push({ ...boardCardObject, x: i, y: 90, isWall: true });
  }

  board.push(
    {
      ...boardCardObject,
      x: 50,
      y: 50,
      isGold: true,
      color: "gold",
    },
    {
      ...boardCardObject,
      x: 440,
      y: 50,
      isGold: true,
      color: "gold",
    },

    {
      ...boardCardObject,
      x: 50,
      y: 240,
      isGold: true,
      color: "gold",
    },

    {
      ...boardCardObject,
      x: 240,
      y: 140,
      isGold: true,
      color: "gold",
    },

    {
      ...boardCardObject,
      x: 500,
      y: 100,
      isGold: true,
      color: "gold",
    },
    {
      ...boardCardObject,
      x: 430,
      y: 240,
      isGold: true,
      color: "gold",
    }
  );

  return board;
}

export const bullets = [
  {
    ...boardCardObject,
    x: 100,
    y: 10,
    originalX: 100,
    originalY: 10,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },
  {
    ...boardCardObject,
    x: 120,
    y: 10,
    originalX: 120,
    originalY: 10,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },
  {
    ...boardCardObject,
    x: 140,
    y: 10,
    originalX: 140,
    originalY: 10,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },
  {
    ...boardCardObject,
    x: 160,
    y: 10,
    originalX: 160,
    originalY: 10,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },
  {
    ...boardCardObject,
    x: 180,
    y: 10,
    originalX: 180,
    originalY: 10,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },
  {
    ...boardCardObject,
    x: 110,
    y: 80,
    originalX: 110,
    originalY: 80,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },

  {
    ...boardCardObject,
    x: 130,
    y: 80,
    originalX: 130,
    originalY: 80,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },

  {
    ...boardCardObject,
    x: 150,
    y: 80,
    originalX: 150,
    originalY: 80,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },

  {
    ...boardCardObject,
    x: 170,
    y: 80,
    originalX: 170,
    originalY: 80,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },

  {
    ...boardCardObject,
    x: 300,
    y: 10,
    originalX: 300,
    originalY: 10,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },
  {
    ...boardCardObject,
    x: 320,
    y: 10,
    originalX: 320,
    originalY: 10,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },
  {
    ...boardCardObject,
    x: 340,
    y: 10,
    originalX: 340,
    originalY: 10,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },
  {
    ...boardCardObject,
    x: 360,
    y: 10,
    originalX: 360,
    originalY: 10,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },
  {
    ...boardCardObject,
    x: 380,
    y: 10,
    originalX: 380,
    originalY: 10,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },
  {
    ...boardCardObject,
    x: 370,
    y: 80,
    originalX: 370,
    originalY: 80,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },
  {
    ...boardCardObject,
    x: 350,
    y: 80,
    originalX: 350,
    originalY: 80,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },
  {
    ...boardCardObject,
    x: 330,
    y: 80,
    originalX: 330,
    originalY: 80,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },
  {
    ...boardCardObject,
    x: 310,
    y: 80,
    originalX: 310,
    originalY: 80,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },
  {
    ...boardCardObject,
    x: 180,
    y: 200,
    originalX: 180,
    originalY: 200,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },
  {
    ...boardCardObject,
    x: 160,
    y: 200,
    originalX: 160,
    originalY: 200,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },

  {
    ...boardCardObject,
    x: 140,
    y: 200,
    originalX: 140,
    originalY: 200,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },
  {
    ...boardCardObject,
    x: 120,
    y: 200,
    originalX: 120,
    originalY: 200,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },

  {
    ...boardCardObject,
    x: 100,
    y: 200,
    originalX: 100,
    originalY: 200,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },

  {
    ...boardCardObject,
    x: 110,
    y: 280,
    originalX: 110,
    originalY: 280,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },

  {
    ...boardCardObject,
    x: 130,
    y: 280,
    originalX: 130,
    originalY: 280,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },

  {
    ...boardCardObject,
    x: 150,
    y: 280,
    originalX: 150,
    originalY: 280,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },

  {
    ...boardCardObject,
    x: 170,
    y: 280,
    originalX: 170,
    originalY: 280,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },

  {
    ...boardCardObject,
    x: 300,
    y: 280,
    originalX: 300,
    originalY: 280,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },
  {
    ...boardCardObject,
    x: 320,
    y: 280,
    originalX: 320,
    originalY: 280,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },
  {
    ...boardCardObject,
    x: 340,
    y: 280,
    originalX: 340,
    originalY: 280,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },
  {
    ...boardCardObject,
    x: 360,
    y: 280,
    originalX: 360,
    originalY: 280,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },
  {
    ...boardCardObject,
    x: 380,
    y: 280,
    originalX: 380,
    originalY: 280,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "up",
  },
  {
    ...boardCardObject,
    x: 370,
    y: 200,
    originalX: 370,
    originalY: 200,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },

  {
    ...boardCardObject,
    x: 350,
    y: 200,
    originalX: 350,
    originalY: 200,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },
  {
    ...boardCardObject,
    x: 330,
    y: 200,
    originalX: 330,
    originalY: 200,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },
  {
    ...boardCardObject,
    x: 310,
    y: 200,
    originalX: 310,
    originalY: 200,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "down",
  },

  {
    ...boardCardObject,
    x: 200,
    y: 170,
    originalX: 200,
    originalY: 170,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "right",
  },
  {
    ...boardCardObject,
    x: 200,
    y: 150,
    originalX: 200,
    originalY: 150,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "right",
  },
  {
    ...boardCardObject,
    x: 200,
    y: 130,
    originalX: 200,
    originalY: 130,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "right",
  },
  {
    ...boardCardObject,
    x: 200,
    y: 110,
    originalX: 200,
    originalY: 110,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "right",
  },
  {
    ...boardCardObject,
    x: 280,
    y: 100,
    originalX: 280,
    originalY: 100,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "left",
  },
  {
    ...boardCardObject,
    x: 280,
    y: 120,
    originalX: 280,
    originalY: 120,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "left",
  },

  {
    ...boardCardObject,
    x: 280,
    y: 160,
    originalX: 280,
    originalY: 160,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "left",
  },

  {
    ...boardCardObject,
    x: 280,
    y: 180,
    originalX: 280,
    originalY: 180,
    isCharacter: false,
    color: "purple",
    isBullet: true,
    direction: "left",
  },
];
